version: '3'
services:
  kringproxy:
    image: "kringproxy:latest"
    ports:
     - "443:443"
    volumes:
     - /etc/ssl:/etc/ssl
     - /var/www:/var/www
    links:
     - kringweb
  kringweb:
    image: "kringweb:latest"
    ports:
     - "4000:4000"
